var jsList = [
    "src/resource.js",
    "src/settings.js",
    "src/models.js",
    "src/facebook.js",
    "src/google.js",
    "src/login.js",
    "src/forgot.js",
    "src/register.js",
    "src/help.js",
    "src/lobby.js",
    "src/game.js",
    "src/gameselect.js",
    "src/tala.js",
    "src/tictactoe.js",
    "src/carogame.js",
    "src/govay.js",
    "src/base64.js"
]
